### PR TITLE
Set CMAKE_EXPORT_COMPILE_COMMANDS if `g:cmake_link_compile_commands` …

### LINKED ISSUE #18: g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON command line argument to cmake.

### PR DESCRIPTION
**Pull request by foonathan**
…is enabled

Fixes #18.

### CODE REVIEW

**Comment by cdelledonne** [comment]
Hi, thanks a lot for submitting this!

Even though the changes do indeed address #18, I though of taking the chance to tidy up `cmake#Generate()` (inside autoload/cmake.vim) a bit. Would you be interested in expanding this PR to do that? If not, I'll merge this as it is, and follow up in another PR when I find some more time.

If instead you are interested, here's a list of things that I had in mind:

1. I would like to slim down the API function `cmake#Generate()`, and move as much logic as possible to `cmake#generate#Run()` (inside autoload/cmake/generate.vim), just to keep the function more simple as the other API functions.

2. The body of `cmake#Generate()` (which would be moved to `cmake#generate#Run()`) uses `cmake#generate#GetBuildType()` to determine if the option `CMAKE_BUILD_TYPE` is present in the command-line options. I would like to expand this `GetBuildType()`, and maybe rename it to something like `FindOption()`, to a more general function that gets a list of command-line options and searches if an option is present, and returns if the option is present and its value.

3. I would like to use this enhanced `cmake#generate#FindOption()` to also determine if the option `CMAKE_EXPORT_COMPILE_COMMANDS` is already present in the command-line options, and only add it if it is not.

Does this make sense to you? Again, if you're not interested, just ignore it.

Looking forward to your reply.

**Comment by cdelledonne** [comment]
One thing, regardless of the above comment: inside doc/cmake.txt, under "CONFIGURATION", could you mention that setting `g:cmake_link_compile_commands` to 1 implies that `CMAKE_EXPORT_COMPILE_COMMANDS` is set to `ON`?

**Comment by foonathan** [comment]
> One thing, regardless of the above comment: inside doc/cmake.txt, under "CONFIGURATION", could you mention that setting g:cmake_link_compile_commands to 1 implies that CMAKE_EXPORT_COMPILE_COMMANDS is set to ON?

Done.

> Does this make sense to you? 

I've tried doing that, but I'm afraid I don't know enough vim script to make it work. For example, what is that `if match()` branch doing in `GetBuildType()`?

**Comment by cdelledonne** [comment]
Yea that function is kind of obscure, some more inline comments would help. Anyway

```vim
if match(a:arglist[0], '\m\C^\w') >= 0
    return [a:arglist[0], 0]
```
The above `match()` checks if the list of arguments `arglist` contains as its first element something that starts with a letter, and for instance not a dash<sup>1</sup>. That is, when the user passes only the build configuration as an argument, e.g. `:CMakeGenerate Release`. In this case, match should return 0, and our function returns the build configuration `a:arglist[0]` and a flag set to `0` to indicate that the option `-DCMAKE_BUILD_TYPE=<config>` is not present in the command-line arguments, and should be added when invoking CMake.

```vim
else
    let l:build_type_arg = matchstr(a:arglist, '\m\CCMAKE_BUILD_TYPE')
    if len(l:build_type_arg)
        return [split(l:build_type_arg, '=')[1], 1]
    else
        return ['', 0]
    endif
endif
```
In the "else" branch, we search for an argument that contains `CMAKE_BUILD_TYPE`. If there is one, and thus `matchstr` returns a non-empty string, we return the build configuration—which is on the right-hand side of the equal sign in the argument `-DCMAKE_BUILD_TYPE=<config>`—and a flag set to `1` to indicate that the option `-DCMAKE_BUILD_TYPE=<config>` is already present in the command-line arguments. If instead the argument is not found, we just return an empty string and a `0`, as the user did not pass any information about the build configuration when calling `:CMakeGenerate`.

Does that clarify enough for you to take a shot at it?

<sup>1</sup> The `\m` flag enables "magic" regexp searching (see `:help /magic`) and the `\C` flag enforces case-sensitive searching. Even if these flags are not always needed, I'm adding them as suggested by the [Google Vimscript Style Guide](https://google.github.io/styleguide/vimscriptguide.xml?showone=Regular_Expressions#Regular_Expressions).

**Comment by foonathan** [comment]
> Does that clarify enough for you to take a shot at it?

I made the PRs while trying out the plugin. I have since decided for a different solution, so I'm not actually going to use the plugin. I will get this and #21 in a state where you can merge them, but I don't think I'll have the time to do the internal refactoring you want here.

**Comment by karlosp** [comment]
Hi @foonathan ,

obviously, I am walking your path. Trying this plugin, finding the exact same issues... Currently, this fix #20 and #21 and solves my problem, but I am just curious what will you use now instead of this plugin? I have a feeling that you are just 2 weeks before me :).

**Comment by foonathan** [comment]
I have written something similar to the "tasks" from space vim (https://spacevim.org/documentation/#tasks) for myself.

**Comment by cdelledonne** [comment]
Implemented in ecd8ecf6555e145d4d5b9540f5eedb6b0038770c

**Pull request closed without merging**
