### PR TITLE
Populate quickfix list after each build

### LINKED ISSUE #8: [Request] Jump to errors
Your plugin its pretty well designed, I like the idea of using an unique window so I don't have to use the :colder command with ALE, also I can switch easily between buildings, but there is one problem, when an error occurs I cant jump to the line with that error.

I guess implementing this with the terminal window it would be like walking trough hell, so maybe it would be nice to have the option to decide if you want to use the terminal window or a quickfix, but I guess you will still have to write a lot of code to accomplish this.

Anyway I open the issue and maybe someone will come up with some idea.

### PR DESCRIPTION
**Pull request by cdelledonne**
Closes #8.

### CODE REVIEW

**Comment by cdelledonne** [comment]
@GGCristo this should satisfy your feature request (#8). I would appreciate if you could checkout this branch and give some feedback. If you can't, don't worry, I'll merge this anyway in a week.

Notice that, for the time being, the quickfix list is generated after each build, but the first error is not jumped to. I'm still thinking whether to add an option for that, or leave it for the user (using e.g. an autocommand event, planned in #7). For now, you have to open the quickfix list/jump to the first error manually.

**Comment by GGCristo** [comment]
Much better, but I still think it should only populate the quickfix when there are errors. Right now even when the compilation exit with 0 errors it will ovewritte the quickfix, in this case it will let an empty quick-fix.

**Comment by cdelledonne** [comment]
> Right now even when the compilation exit with 0 errors it will ovewritte the quickfix

Isn't this a good thing? Otherwise you would have quickfix entries which point to errors that are not there anymore. Why would you want to keep old quickfix entries around?

**Comment by GGCristo** [comment]
Yes you are right, I forgot that the quickfix doesn't work in real time, so you have to compile again to update it. I said so because a lot of plugins use the quickfix so I was thinking in the case where you have the quicfix with info from other plugin and then you compile and that info its "lost", but its not a big deal.

**Comment by cdelledonne** [comment]
Previous quickfix lists are not lost, Vim-CMake uses its own. You can use `:chistory` to find out what quickfix lists exist, and `:colder` and `:cnewer` to switch to one of those. Vim-CMake uses `:colder` and `:cnewer` to switch to its quickfix list after each build, and does not overwrite any of the existing lists.

For example, you run `:CMakeBuild`, which returns one error. If you run `:chistory`, you get something like
```
> error list 1 of 1; 1 errors     CMakeBuild
```

Then, you run a command from another plugin that creates another quickfix list. Then `:chistory` gives
```
  error list 1 of 2; 1 errors     CMakeBuild
> error list 2 of 2; 51 errors    Some other plugin's list
```

If you fix the build error and run `:CMakeBuild` again, `:chistory` might give
```
> error list 1 of 2; 0 errors     CMakeBuild
  error list 2 of 2; 51 errors    Some other plugin's list
```

that is, Vim-CMake's quickfix list is now active, but the other list can be switched to with `:cnewer`.

**Pull request merged**
